import Head from 'next/head'
import VerticalCard from 'components/Card/VerticalCard'
import { CARDS } from 'data/inicio'
import Gallery from 'components/Gallery'
import HorizontalCard from 'components/Card/HorizontalCard'
export default function Home() {
  return (
    <>
      <Head>
        <title>Hotel Manantial de Churin</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Gallery />
      <div className='py-8'>
        <div className='grid grid-cols-1 justify-items-center md:grid-cols-2 xl:grid-cols-3 gap-4'>
          {CARDS.map(({ title, description, tags, img, id, url }) => (
            <VerticalCard
              title={title}
              description={description}
              tags={tags}
              img={img}
              key={id}
              url={url}
            />
          ))}
        </div>
      </div>
      <HorizontalCard />
    </>
  )
}
