import Head from 'next/head'
import ListOfCards from 'components/ListOfCards'
import { CARDS_INICIO, INFO_CARD_INICIO } from 'data/inicio'
import InfoCard from 'components/InfoCard'
import Title from 'components/Title'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hotel Manantial de Churin</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='mb-6'>
        <ListOfCards info={CARDS_INICIO} />
      </div>
      <Title>¿Que hacer en Churín?</Title>
      <InfoCard
        title={INFO_CARD_INICIO.title}
        description={INFO_CARD_INICIO.description}
        img={INFO_CARD_INICIO.img}
      />
    </>
  )
}
